# Site settings
title: Ed Hagen
scholartitle: Ed Hagen's blog
description: > # this means to ignore newlines until "baseurl:"
  A blog about evolutionary medicine, evolutionary psychology, 
  human behavioral ecology, and human biology.
url: http://grasshoppermouse.github.io
# Build settings
markdown: kramdown
