# Site settings
title: Ed Hagen
description: > # this means to ignore newlines until "baseurl:"
  A blog about evolutionary medicine, evolutionary psychology, 
  human behavioral ecology, and human biology.
baseurl: ""
# Build settings
markdown: kramdown
